/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpasiboRouteImport } from './routes/spasibo'
import { Route as KvizSimpleRouteImport } from './routes/kviz-simple'
import { Route as KvizRouteImport } from './routes/kviz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogMobilnyeSkladyIzRefkonteynerovRouteImport } from './routes/blog.mobilnye-sklady-iz-refkonteynerov'

const SpasiboRoute = SpasiboRouteImport.update({
  id: '/spasibo',
  path: '/spasibo',
  getParentRoute: () => rootRouteImport,
} as any)
const KvizSimpleRoute = KvizSimpleRouteImport.update({
  id: '/kviz-simple',
  path: '/kviz-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const KvizRoute = KvizRouteImport.update({
  id: '/kviz',
  path: '/kviz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogMobilnyeSkladyIzRefkonteynerovRoute =
  BlogMobilnyeSkladyIzRefkonteynerovRouteImport.update({
    id: '/blog/mobilnye-sklady-iz-refkonteynerov',
    path: '/blog/mobilnye-sklady-iz-refkonteynerov',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kviz': typeof KvizRoute
  '/kviz-simple': typeof KvizSimpleRoute
  '/spasibo': typeof SpasiboRoute
  '/blog/mobilnye-sklady-iz-refkonteynerov': typeof BlogMobilnyeSkladyIzRefkonteynerovRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kviz': typeof KvizRoute
  '/kviz-simple': typeof KvizSimpleRoute
  '/spasibo': typeof SpasiboRoute
  '/blog/mobilnye-sklady-iz-refkonteynerov': typeof BlogMobilnyeSkladyIzRefkonteynerovRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kviz': typeof KvizRoute
  '/kviz-simple': typeof KvizSimpleRoute
  '/spasibo': typeof SpasiboRoute
  '/blog/mobilnye-sklady-iz-refkonteynerov': typeof BlogMobilnyeSkladyIzRefkonteynerovRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kviz'
    | '/kviz-simple'
    | '/spasibo'
    | '/blog/mobilnye-sklady-iz-refkonteynerov'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kviz'
    | '/kviz-simple'
    | '/spasibo'
    | '/blog/mobilnye-sklady-iz-refkonteynerov'
  id:
    | '__root__'
    | '/'
    | '/kviz'
    | '/kviz-simple'
    | '/spasibo'
    | '/blog/mobilnye-sklady-iz-refkonteynerov'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KvizRoute: typeof KvizRoute
  KvizSimpleRoute: typeof KvizSimpleRoute
  SpasiboRoute: typeof SpasiboRoute
  BlogMobilnyeSkladyIzRefkonteynerovRoute: typeof BlogMobilnyeSkladyIzRefkonteynerovRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spasibo': {
      id: '/spasibo'
      path: '/spasibo'
      fullPath: '/spasibo'
      preLoaderRoute: typeof SpasiboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kviz-simple': {
      id: '/kviz-simple'
      path: '/kviz-simple'
      fullPath: '/kviz-simple'
      preLoaderRoute: typeof KvizSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kviz': {
      id: '/kviz'
      path: '/kviz'
      fullPath: '/kviz'
      preLoaderRoute: typeof KvizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mobilnye-sklady-iz-refkonteynerov': {
      id: '/blog/mobilnye-sklady-iz-refkonteynerov'
      path: '/blog/mobilnye-sklady-iz-refkonteynerov'
      fullPath: '/blog/mobilnye-sklady-iz-refkonteynerov'
      preLoaderRoute: typeof BlogMobilnyeSkladyIzRefkonteynerovRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KvizRoute: KvizRoute,
  KvizSimpleRoute: KvizSimpleRoute,
  SpasiboRoute: SpasiboRoute,
  BlogMobilnyeSkladyIzRefkonteynerovRoute:
    BlogMobilnyeSkladyIzRefkonteynerovRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
